# Generated by Django 2.2 on 2019-04-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190406_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/static/pics/default.png', upload_to='static/pics/'),
        ),
    ]
