# Generated by Django 2.2 on 2019-04-20 16:44

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190420_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='pics/default.png', upload_to='pics/'),
        ),
    ]
