# Generated by Django 2.2 on 2019-04-06 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_photomodel_upload_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photomodel',
            name='upload_time',
        ),
    ]
