# Generated by Django 2.2 on 2019-04-06 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_remove_photomodel_upload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomodel',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
