# Generated by Django 2.2 on 2019-04-06 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_photomodel_upload_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photomodel',
            old_name='upload_time',
            new_name='timestamp',
        ),
    ]
